/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Asus
 */
public class Aplication extends javax.swing.JFrame {

    /** Creates new form Aplication */
    public Aplication() {
        initComponents();
        cBoxAll.setSelected(true);
        cBoxRed.setSelected(true);
        cBoxBlue.setSelected(true);
        cBoxGreen.setSelected(true);
        esqID.setSelected(true);
        mostrador1.setIconPosition(mostrador1.getWidth() -74 ,mostrador1.getHeight() -74);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoEsquina = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        esqSI = new javax.swing.JRadioButton();
        esqSD = new javax.swing.JRadioButton();
        esqII = new javax.swing.JRadioButton();
        esqID = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        cBoxRed = new javax.swing.JCheckBox();
        cBoxBlue = new javax.swing.JCheckBox();
        cBoxGreen = new javax.swing.JCheckBox();
        cBoxAll = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        mostrador1 = new Mostrador();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        grupoEsquina.add(esqSI);
        esqSI.setText("Esquina Sup-Izq");
        esqSI.setActionCommand("Esquina Izq-Sup");
        esqSI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                esqSIActionPerformed(evt);
            }
        });

        grupoEsquina.add(esqSD);
        esqSD.setText("Esquina Sup-Der");
        esqSD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                esqSDActionPerformed(evt);
            }
        });

        grupoEsquina.add(esqII);
        esqII.setText("Esquina Inf-Izq");
        esqII.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                esqIIActionPerformed(evt);
            }
        });

        grupoEsquina.add(esqID);
        esqID.setText("Esquina Inf-Der");
        esqID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                esqIDActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(esqII, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(esqID, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(esqSI)
                    .add(esqSD, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(esqSI)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(esqSD)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(esqII)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(esqID)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        cBoxRed.setText("Rojo");
        cBoxRed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cBoxRedActionPerformed(evt);
            }
        });

        cBoxBlue.setText("Azul");
        cBoxBlue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cBoxBlueActionPerformed(evt);
            }
        });

        cBoxGreen.setText("Verde");
        cBoxGreen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cBoxGreenActionPerformed(evt);
            }
        });

        cBoxAll.setText("Todos");
        cBoxAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cBoxAllActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel3Layout = new org.jdesktop.layout.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(cBoxRed)
                    .add(cBoxBlue)
                    .add(cBoxGreen))
                .addContainerGap(52, Short.MAX_VALUE))
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(cBoxAll)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .add(cBoxRed)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(cBoxBlue)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(cBoxGreen)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 8, Short.MAX_VALUE)
                .add(cBoxAll)
                .addContainerGap())
        );

        jLabel1.setText("Posición del icono");

        jLabel2.setText("Canales de color");

        org.jdesktop.layout.GroupLayout jPanel2Layout = new org.jdesktop.layout.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .add(22, 22, 22)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel1))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 60, Short.MAX_VALUE)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel2Layout.createSequentialGroup()
                        .add(jLabel2)
                        .add(44, 44, 44))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel2Layout.createSequentialGroup()
                        .add(jPanel3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(20, 20, 20))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel1)
                    .add(jLabel2))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(jPanel3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        mostrador1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        org.jdesktop.layout.GroupLayout mostrador1Layout = new org.jdesktop.layout.GroupLayout(mostrador1);
        mostrador1.setLayout(mostrador1Layout);
        mostrador1Layout.setHorizontalGroup(
            mostrador1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 599, Short.MAX_VALUE)
        );
        mostrador1Layout.setVerticalGroup(
            mostrador1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 352, Short.MAX_VALUE)
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(24, 24, 24)
                .add(jPanel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap(172, Short.MAX_VALUE)
                .add(mostrador1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(22, 22, 22))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(7, 7, 7)
                .add(jPanel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(31, 31, 31)
                .add(mostrador1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void esqSIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_esqSIActionPerformed
        // TODO add your handling code here:
       if (esqSI.isSelected())
        mostrador1.setIconPosition(10,10);
    }//GEN-LAST:event_esqSIActionPerformed

    private void cBoxRedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cBoxRedActionPerformed
        // TODO add your handling code here:
        /*if (cBoxRed.isSelected()){
            mostrador1.invertMode(true, cBoxBlue.isSelected(), cBoxGreen.isSelected());
        } else {
            mostrador1.invertMode(false, cBoxBlue.isSelected(), cBoxGreen.isSelected());
            cBoxAll.setSelected(false);
        }*/
        if(!cBoxBlue.isSelected() && !cBoxGreen.isSelected() && !cBoxRed.isSelected()) cBoxRed.setSelected(true);
        mostrador1.invertMode(cBoxRed.isSelected(), cBoxGreen.isSelected(), cBoxBlue.isSelected());
        if (!cBoxRed.isSelected()) cBoxAll.setSelected(false);
        if(cBoxRed.isSelected()&& cBoxBlue.isSelected()&& cBoxGreen.isSelected()) 
            cBoxAll.setSelected(true);
        
    }//GEN-LAST:event_cBoxRedActionPerformed

    private void cBoxAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cBoxAllActionPerformed
        // TODO add your handling code here:
        if(cBoxAll.isSelected()){
            mostrador1.invertMode(true, true, true);
            cBoxRed.setSelected(true);
            cBoxBlue.setSelected(true);
            cBoxGreen.setSelected(true);
        }else{
            cBoxAll.setSelected(true);
        }
    }//GEN-LAST:event_cBoxAllActionPerformed

    private void cBoxBlueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cBoxBlueActionPerformed
        // TODO add your handling code here:
        if(!cBoxBlue.isSelected() && !cBoxGreen.isSelected() && !cBoxRed.isSelected()) cBoxBlue.setSelected(true);
        mostrador1.invertMode(cBoxRed.isSelected(), cBoxGreen.isSelected(), cBoxBlue.isSelected());
        if(cBoxRed.isSelected()&& cBoxBlue.isSelected()&& cBoxGreen.isSelected()) 
            cBoxAll.setSelected(true);
        if (!cBoxBlue.isSelected()) cBoxAll.setSelected(false);
        
    }//GEN-LAST:event_cBoxBlueActionPerformed

    private void cBoxGreenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cBoxGreenActionPerformed
        // TODO add your handling code here:
        if(!cBoxBlue.isSelected() && !cBoxGreen.isSelected() && !cBoxRed.isSelected()) cBoxGreen.setSelected(true);
        mostrador1.invertMode(cBoxRed.isSelected(), cBoxGreen.isSelected(), cBoxBlue.isSelected());
        if(cBoxRed.isSelected()&& cBoxBlue.isSelected()&& cBoxGreen.isSelected()) 
            cBoxAll.setSelected(true);
        if (!cBoxGreen.isSelected()) cBoxAll.setSelected(false);
        
    }//GEN-LAST:event_cBoxGreenActionPerformed

    private void esqSDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_esqSDActionPerformed
        // TODO add your handling code here:
        if (esqSD.isSelected())
            mostrador1.setIconPosition(mostrador1.getWidth() -74 , 10);
    }//GEN-LAST:event_esqSDActionPerformed

    private void esqIIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_esqIIActionPerformed
        // TODO add your handling code here:
        if (esqII.isSelected())
            mostrador1.setIconPosition(10 ,mostrador1.getHeight() -74);
        
    }//GEN-LAST:event_esqIIActionPerformed

    private void esqIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_esqIDActionPerformed
        // TODO add your handling code here:
        if (esqID.isSelected())
            mostrador1.setIconPosition(mostrador1.getWidth() -74 ,mostrador1.getHeight() -74);
    }//GEN-LAST:event_esqIDActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Aplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Aplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Aplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Aplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Aplication().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox cBoxAll;
    private javax.swing.JCheckBox cBoxBlue;
    private javax.swing.JCheckBox cBoxGreen;
    private javax.swing.JCheckBox cBoxRed;
    private javax.swing.JRadioButton esqID;
    private javax.swing.JRadioButton esqII;
    private javax.swing.JRadioButton esqSD;
    private javax.swing.JRadioButton esqSI;
    private javax.swing.ButtonGroup grupoEsquina;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private Mostrador mostrador1;
    // End of variables declaration//GEN-END:variables

}
