/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Asus
 */
import java.awt.Graphics;
import java.awt.Point;
import java.awt.image.BufferedImage;
import java.awt.image.ColorModel;
import java.awt.image.WritableRaster;
import java.net.URL;
import javax.imageio.ImageIO;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Cayetano
 */
public class Mostrador extends javax.swing.JPanel {

    private BufferedImage img, img_copy, icon; // Esto es una imagen con la propiedad de escribir sobre ella y poder modificarla
    Point iconPosition;
    /**
     * Creates new form myJPanel
     */
    public Mostrador() {
        initComponents();
        try{
            img = ImageIO.read(new URL("https://www.dictando.com/wp-content/uploads/2018/07/dictado-mi-casa-A1.jpg"));
            icon = ImageIO.read(new URL("https://png.pngtree.com/element_our/sm/20180626/sm_5b321ca7a1ca4.png"));
            img_copy = deepCopy(img);
//Si queremos leer cualquier cosa
        } catch (Exception e){
            System.out.print(e);
        }
        iconPosition = new Point(10,10);
    }

    static BufferedImage deepCopy(BufferedImage bi) {
        ColorModel cm = bi.getColorModel();
        boolean isAlphaPremultiplied = cm.isAlphaPremultiplied();
        WritableRaster raster = bi.copyData(null);
        return new BufferedImage(cm, raster, isAlphaPremultiplied, null);
    }

    public void invertMode(boolean c_red, boolean c_green, boolean c_blue){
      //Cada vez que hagamos una modificación hacemos dos bucles para recorrer filas y columnas
        int mask = 0x000000;
        if (c_red) mask = mask | 0xFF0000;
        if (c_green) mask = mask | 0x00FF00;
        if (c_blue) mask = mask | 0x0000FF;
        //Con el set RGB ponemos en cada pixel la máscara para activarlo o desactivarlo
        img_copy = deepCopy(img);
        for (int j=0;j<img.getHeight();j++){
            for (int i=0;i<img.getWidth();i++){
                img_copy.setRGB(i, j, mask & img.getRGB(i, j));
            }
        }
        repaint();
    }
/*
  La imagen alterada lo primero y el logotipo lo segundo,
  siendo sus primeros componentes el tamaño y localización
*/
    @Override
    protected void paintComponent(Graphics g){
        super.paintComponent(g);
        g.drawImage(img_copy, 0, 0, this);
        g.drawImage(icon, (int)iconPosition.getX(),(int)iconPosition.getY(),
               64,64, this);
        //                x,y,dimensionX,dimensionY
    }
    public void setIconPosition(int x, int y){
        iconPosition = new Point(x,y);
        repaint();
    }
    public int getImgHeight(){
        return img.getHeight();
    }
    public int getImgWidth(){
        return img.getWidth();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
